# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybPwBUgmm3nShTIzZBkrBgz5JP7_Dp7M
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

df = pd.read_csv('/content/SVMtrain.csv')
df.head()

df.shape

df.columns

df1 = df.drop(['PassengerId'],axis='columns')
df1.shape

df1.isnull().sum()

df1.head(10)

df2 = df1.drop_duplicates()
df2.shape

import seaborn as sns

sns.boxplot(df2['Fare'])
plt.show()

Q1 = df2['Fare'].quantile(0.25)
Q3 = df2['Fare'].quantile(0.75)
IQR = Q3 - Q1

outliers = df2[(df2['Fare'] < Q1 - 1.5 * IQR) | (df2['Fare'] > Q3 + 1.5 * IQR)]
# Identify potential outliers

# Remove outliers from the DataFrame
df3 = df2[~((df2['Fare'] < Q1 - 1.5 * IQR) | (df2['Fare'] > Q3 + 1.5 * IQR))]

df3.head()

df3.shape

df3['Sex'] = df3['Sex'].fillna('0')

df3['Sex'] = df3['Sex'].map({'Male': 0, 'female': 1, 'Unknown': 2})

df3.head()

df3['Sex'] = df3['Sex'].fillna('0')

df3

df3.head(8)

from sklearn.model_selection import train_test_split

X = df3.drop('Survived', axis=1)
y = df3['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

